php开发环境运行代码git提交钩子.代码重复检测

diff --git a/dev/roles/php/files/pre-commit b/dev/roles/php/files/pre-commit
--- a/dev/roles/php/files/pre-commit
+++ b/dev/roles/php/files/pre-commit
@@ -17,6 +17,17 @@ then
 fi
 echo -e "code style check: ${GREEN}success${NORMAL}"
 
+# 运行重复代码检查
+echo -e "php copy paste detect: ${YELLOW}start${NORMAL}"
+docker exec web-phpfpm vendor/bin/phpcpd ./Application
+
+if [ $? -ne 0 ]
+then
+  echo -e "php copy paste detect: ${RED}fail${NORMAL}"
+  exit 1
+fi
+echo -e "php copy paste detect: ${GREEN}success${NORMAL}"
+
 # 运行单元测试检查 
 echo -e "unit test: ${YELLOW}start${NORMAL}"
 docker exec web-phpfpm vendor/bin/phpunit
